// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7GyV8kvreDDZcexfhuIvT05JAzCFOzo',
    appId: '1:730083418400:web:16c48d05af5cfa78caf745',
    messagingSenderId: '730083418400',
    projectId: 'srockmusic-67339',
    authDomain: 'srockmusic-67339.firebaseapp.com',
    storageBucket: 'srockmusic-67339.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFRYOhc0Hpb2t2r6fliXboLS-f6zfLaus',
    appId: '1:730083418400:android:71a48e3916ff0d0dcaf745',
    messagingSenderId: '730083418400',
    projectId: 'srockmusic-67339',
    storageBucket: 'srockmusic-67339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOeKYBUCdvbXGBmCX-5o19cXPCO49jikc',
    appId: '1:730083418400:ios:b838a11a50b98274caf745',
    messagingSenderId: '730083418400',
    projectId: 'srockmusic-67339',
    storageBucket: 'srockmusic-67339.firebasestorage.app',
    iosBundleId: 'com.example.srockmusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOeKYBUCdvbXGBmCX-5o19cXPCO49jikc',
    appId: '1:730083418400:ios:b838a11a50b98274caf745',
    messagingSenderId: '730083418400',
    projectId: 'srockmusic-67339',
    storageBucket: 'srockmusic-67339.firebasestorage.app',
    iosBundleId: 'com.example.srockmusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP7GyV8kvreDDZcexfhuIvT05JAzCFOzo',
    appId: '1:730083418400:web:01a5b99ca0338a5dcaf745',
    messagingSenderId: '730083418400',
    projectId: 'srockmusic-67339',
    authDomain: 'srockmusic-67339.firebaseapp.com',
    storageBucket: 'srockmusic-67339.firebasestorage.app',
  );
}
